[package]
name = "flea"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
pollster = "0.4.0"
winit = "0.30.7"
vello = { git = "https://github.com/linebender/vello", rev = "8a84a4abf7aa" }
petgraph = "0.6.5"
